export const CLOSE_LOAD_PAGE = 'CLOSE_LOAD_PAGE'
export const PUSH_FILES = 'PUSH_FILES'
export const SHOW_LOAD_PAGE = 'SHOW_LOAD_PAGE'

export const DATA_FORM = 'DATA_FORM'

export const PUSH_FILE = 'PUSH_FILE'
export const CLEAN_FORM_CONTROLS = 'CLEAN_FORM_CONTROLS'

export const FILE_WILL_DELETED = 'FILE_WILL_DELETED'
